### PR TITLE
adds support for promotion; support chess960

### PR DESCRIPTION
**Pull request by hongyihu**
- Adds UI support for promoting a pawn
- Support Chess960 starting positions. Unfortunately correct castling support for Chess960 is not yet available in chess.js

### CODE REVIEW

**Comment by hongyihu** [comment]
@isg want to take a look?

**Review by isg — COMMENTED** [review]
Just curious, does chess.js have an option that auto-promotes any pawn to a queen? I know not technically correct, but if it does it might save us some trouble...

**Comment by hongyihu** [comment]
We can hard-code promotion to queen. Is there something wrong with the UI for the promotion selection? I know it's a little rough but it seems serviceable.

**Comment by isg** [comment]
No was just curious! Can you include a screenshot?

**Comment by hongyihu** [comment]
Sure!

Right before promotion

Screen Shot 2022-12-05 at 17 45 36

Selecting a piece to promote to

Screen Shot 2022-12-05 at 17 45 50

Promoted to a rook

Screen Shot 2022-12-05 at 17 46 05

**Comment by hongyihu** [comment]
For black:

Screen Shot 2022-12-05 at 17 48 55

Promoted to queen:

Screen Shot 2022-12-05 at 17 49 01

**Pull request merged**
